### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by k0st1an** [badoux/checkmail#19]
When the host is existed but port not available. Example: `g2mail.com`:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1187ba2]

goroutine 1 [running]:
net/smtp.(*Client).Close(0x0, 0x122d620, 0xc4200a0370)
	/usr/local/go/src/net/smtp/smtp.go:76 +0x22
github.com/k0st1an/tests/emailcheck/vendor/github.com/badoux/checkmail.ValidateHost(0x7ffeefbff97c, 0x13, 0x122dc20, 0xc42005aee0)
	/Users/k0st1an/develop/golang/src/github.com/k0st1an/tests/emailcheck/vendor/github.com/badoux/checkmail/checkmail.go:57 +0x441
main.emailIsValid(0x7ffeefbff97c, 0x13, 0x0)
	/Users/k0st1an/develop/golang/src/github.com/k0st1an/tests/emailcheck/emailcheck.go:26 +0x57
main.main()
	/Users/k0st1an/develop/golang/src/github.com/k0st1an/tests/emailcheck/emailcheck.go:15 +0x42
```

**Comment by tserkov** [comment]
Ran into this earlier today.  I believe an alternative solution would be to simply move the `defer` to after the error check.

```golang
client, err := smtp.Dial(fmt.Sprintf("%s:%d", mx[0].Host, 25))
if err != nil {
	return NewSmtpError(err)
}
defer client.Close()
```

**Comment by k0st1an** [comment]
Yes, you are right.

**Comment by egroj97** [comment]
Has anyone made a pool request about this?
